(** This file is used in [sudokulogic.ml] to generate 16x16 Sudoku puzzles. Due
    to time constraints, these boards are statically typed *)

open Sudokutypes

(* Auto-generated 16 pre-generated 16x16 puzzles *)
let boards : cell array array list =
  [
    (* Board 1 *)
    [|
      [|
        Initial 14;
        Empty;
        Initial 9;
        Initial 8;
        Empty;
        Empty;
        Empty;
        Initial 4;
        Initial 1;
        Initial 5;
        Empty;
        Empty;
        Initial 2;
        Initial 6;
        Empty;
        Initial 16;
      |];
      [|
        Empty;
        Initial 7;
        Empty;
        Initial 16;
        Initial 3;
        Empty;
        Initial 8;
        Initial 13;
        Initial 12;
        Initial 4;
        Initial 11;
        Empty;
        Initial 15;
        Initial 14;
        Empty;
        Empty;
      |];
      [|
        Initial 13;
        Empty;
        Initial 4;
        Empty;
        Empty;
        Empty;
        Empty;
        Empty;
        Initial 15;
        Empty;
        Initial 14;
        Initial 10;
        Initial 5;
        Empty;
        Empty;
        Empty;
      |];
      [|
        Initial 11;
        Empty;
        Initial 10;
        Initial 6;
        Empty;
        Initial 15;
        Initial 1;
        Empty;
        Initial 2;
        Initial 16;
        Empty;
        Initial 9;
        Initial 7;
        Empty;
        Initial 3;
        Empty;
      |];
      [|
        Empty;
        Initial 2;
        Initial 7;
        Initial 1;
        Initial 16;
        Initial 8;
        Empty;
        Initial 12;
        Initial 9;
        Initial 11;
        Empty;
        Empty;
        Empty;
        Empty;
        Empty;
        Initial 10;
      |];
      [|
        Initial 16;
        Initial 10;
        Initial 13;
        Empty;
        Initial 9;
        Initial 4;
        Empty;
        Initial 1;
        Initial 5;
        Initial 8;
        Empty;
        Empty;
        Initial 12;
        Empty;
        Initial 6;
        Initial 7;
      |];
      [|
        Initial 12;
        Empty;
        Empty;
        Initial 5;
        Empty;
        Initial 11;
        Empty;
        Empty;
        Empty;
        Initial 2;
        Empty;
        Initial 7;
        Empty;
        Initial 3;
        Empty;
        Initial 9;
      |];
      [|
        Initial 9;
        Empty;
        Empty;
        Empty;
        Initial 5;
        Initial 13;
        Empty;
        Empty;
        Initial 10;
        Initial 12;
        Initial 1;
        Empty;
        Empty;
        Initial 16;
        Initial 2;
        Initial 4;
      |];
      [|
        Empty;
        Empty;
        Empty;
        Empty;
        Initial 10;
        Empty;
        Initial 12;
        Initial 14;
        Initial 3;
        Initial 13;
        Initial 4;
        Empty;
        Initial 16;
        Initial 8;
        Empty;
        Empty;
      |];
      [|
        Empty;
        Initial 8;
        Empty;
        Empty;
        Empty;
        Empty;
        Empty;
        Empty;
        Empty;
        Initial 15;
        Initial 12;
        Empty;
        Empty;
        Initial 9;
        Empty;
        Initial 6;
      |];
      [|
        Initial 1;
        Initial 13;
        Initial 16;
        Initial 2;
        Empty;
        Initial 6;
        Empty;
        Initial 9;
        Initial 11;
        Initial 14;
        Empty;
        Empty;
        Initial 3;
        Empty;
        Initial 4;
        Empty;
      |];
      [|
        Initial 3;
        Initial 11;
        Initial 12;
        Empty;
        Initial 4;
        Empty;
        Empty;
        Empty;
        Initial 6;
        Empty;
        Initial 7;
        Initial 8;
        Initial 13;
        Empty;
        Empty;
        Initial 14;
      |];
      [|
        Initial 10;
        Empty;
        Empty;
        Initial 14;
        Empty;
        Initial 7;
        Initial 5;
        Initial 2;
        Initial 13;
        Initial 6;
        Empty;
        Initial 4;
        Initial 11;
        Initial 1;
        Initial 8;
        Empty;
      |];
      [|
        Empty;
        Empty;
        Initial 11;
        Initial 12;
        Initial 13;
        Empty;
        Empty;
        Initial 3;
        Empty;
        Empty;
        Initial 15;
        Empty;
        Initial 9;
        Initial 7;
        Empty;
        Initial 2;
      |];
      [|
        Empty;
        Initial 9;
        Initial 1;
        Empty;
        Initial 15;
        Empty;
        Initial 6;
        Empty;
        Empty;
        Empty;
        Initial 2;
        Initial 11;
        Initial 4;
        Empty;
        Empty;
        Empty;
      |];
      [|
        Empty;
        Initial 4;
        Initial 3;
        Empty;
        Empty;
        Empty;
        Initial 10;
        Initial 8;
        Empty;
        Empty;
        Empty;
        Initial 12;
        Empty;
        Initial 13;
        Empty;
        Empty;
      |];
    |];
  ]
